# Generated by Django 5.2.8 on 2025-11-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default='00000-0000', max_length=10),
            preserve_default=False,
        ),
    ]
